[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-get-available-sensors",
    "allow-start-sensors",
    "allow-stop-sensors",
    "allow-registerListener",
    "allow-unregister-listener",
    "allow-create-sensor-data",
    "allow-delete-sensor-data",
    "allow-get-grouped-sensor-data",
    "allow-create-group",
    "allow-get-group",
    "allow-get-groups",
    "allow-delete-group",
]
